### ISSUE TITLE
Translate JavaScript - Introduction to JavaScript

### ISSUE THREAD

**Issue by ChaiyoKung** [ThaiProgrammer/tpa-roadmap#17]
### Feature Description

Content List:
- Introduction to JavaScript
  - What is JavaScript?
  - History of JavaScript
  - JavaScript Versions
  - How to run JavaScript

**Comment by pavitpim40** [comment]
Can you assign this issue to me @ChaiyoKung

**Comment by ChaiyoKung** [comment]
@pavitpim40 Now I'm alreay done this issue.

**Comment by pavitpim40** [comment]
ok :)
